<?php
/**
 * Event hero image at the top of the white content card.
 *
 * The image renders at 600 wide, height up to $max_height, sharp on
 * retina because the source is the 1200x600 centre-cropped size
 * generated by add_image_size('kdna-events-email-header').
 *
 * Hides entirely when no URL is resolved, so the card opens directly
 * with the heading.
 *
 * Expects:
 *   $header_image_url   Absolute URL or ''.
 *   $header_image_max_h Max render height in px.
 *   $event_title        For the alt attribute.
 *   $card_radius        Border radius in px for the top corners.
 *
 * @package KDNA_Events
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( '' === (string) $header_image_url ) {
	return;
}

$max_h = max( 80, min( 600, (int) $header_image_max_h ) );
$rad   = max( 0, (int) $card_radius );
?>
<tr>
	<td class="kdna-events-email-hero" style="padding:0;line-height:0;font-size:0;">
		<img
			src="<?php echo esc_url( $header_image_url ); ?>"
			alt="<?php echo esc_attr( (string) $event_title ); ?>"
			width="600"
			style="display:block;width:100%;max-width:600px;height:auto;max-height:<?php echo esc_attr( (string) $max_h ); ?>px;border:0;outline:none;text-decoration:none;border-top-left-radius:<?php echo esc_attr( (string) $rad ); ?>px;border-top-right-radius:<?php echo esc_attr( (string) $rad ); ?>px;"
		/>
	</td>
</tr>
